-- 统一审计列命名为 create_time / update_time，并增加软删除 delete_time

-- users
ALTER TABLE users
    CHANGE COLUMN created_at create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHANGE COLUMN updated_at update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ADD COLUMN delete_time DATETIME NULL DEFAULT NULL COMMENT '软删除时间（NULL表示未删除）';

-- locations
ALTER TABLE locations
    CHANGE COLUMN created_at create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHANGE COLUMN updated_at update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ADD COLUMN delete_time DATETIME NULL DEFAULT NULL COMMENT '软删除时间（NULL表示未删除）';

-- records
ALTER TABLE records
    CHANGE COLUMN created_at create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHANGE COLUMN updated_at update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ADD COLUMN delete_time DATETIME NULL DEFAULT NULL COMMENT '软删除时间（NULL表示未删除）';
